# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 600
cpus_per_task: 10
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 64
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: devlab  # devlab, prioritylab, learnlab
signal_delay_s: 120
max_num_timeout: 0
array_parallelism: 256