_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_dino_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/models/dino_habitat/dino_vit_base_patch16_omnidata_100_epochs.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: dino
  model: vit_base_patch16
  data: omnidata
  comment: 100_epochs
