name: forward_model
lr: 1e-4
n_epochs: 500
obj_state_type: img_r3m
use_ftpos: False
n_epoch_every_save: 50
hidden_dims: 4096-2048
path_to_decoder_ckpt: /private/home/clairelchen/projects/trifinger_claire/multirun/2022-08-15/exp_decoder_exp_1-2022-08-15-18-17-52/2/ckpts/epoch_2000_ckpt.pth
