[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=60.8.1",
    "wheel>=0.37.1",
]

[tool.usort]
first_party_detection = false

[tool.black]
target-version = ["py38"]
