_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_contrastive_vit
  checkpoint_path: /checkpoint/yixinlin/eaif/models/adaptation/moco_modified/mae_vitb_scaling1_hgsp5p_v1.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  pretrain_algo: "mae"
  adapt_algo: "moco++"
  starting_pt: "mae_vitb_ego_inav_233_epochs"
  pretrain_data:
    - ego
    - inav
  adapt_data: "5% HGSP"
  model: vit_base_patch16
  comment: HGSP representation finetuned from MAE model trained on scaling datasets
