_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_mae_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/models/mae_habitat/mae_vit_base_patch16_human_demos_96_epochs.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_base_patch16
  data: human_demos
  comment: 96_epochs
