_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_mae_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/models/mae_hgsp_ego4d/mae_vit_base_patch16_HGSP_ego4d_800_epochs.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_base_patch16
  data:
    - HGSP
    - ego4d
  comment: 800_epochs
