version: 2.1

commands:
  initialize:
    steps:
      - run:
          name: Initialize Git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Delete extraneous circleci environment file
          # This is extremely important for some esoteric $PATH issues involving mrp, Python subprocess, and /bin/bash
          command: rm -rf ~/.circlerc
      - run:
          name: Install Miniconda3
          command: |
            if [ ! -d ~/miniconda3 ]; then
              wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
              /bin/bash ~/miniconda.sh -b -p ~/miniconda3
              rm ~/miniconda.sh
            fi
            sudo ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
            echo ". ~/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc
            echo "conda activate base" >> ~/.bashrc
      - run:
          name: Install mamba
          command: |
            . ~/miniconda3/bin/activate
            conda install -y -c conda-forge mamba -n base
      - run:
          name: Create conda environment
          command: |
            . ~/miniconda3/bin/activate
            [ -d ~/miniconda3/envs/eaif ] || mamba env create -f environment.yml

jobs:
  load-models:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.small
    steps:
      - checkout
      - initialize
      - run:
          name: Install eaif-models
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            pip install -e ./eaif-models
      - run:
          name: Run CIFAR linear probe
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            pytest eaif-models/tests/test_model_loading.py --nocluster
  cifar-linprobe:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - initialize
      - run:
          name: Install eaif-models
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            pip install -e ./eaif-models
      - restore_cache:
          key: cifar-linprobe-data-{{ .Branch }}
      - run:
          name: Download CIFAR dataset
          command: |
            if [ ! -f ./data/cifar-10-python.tar.gz ]
            then
              . ~/miniconda3/bin/activate
              conda activate eaif
              python -c "import torchvision; torchvision.datasets.CIFAR10(root='./data', download=True)"
            fi
      - save_cache:
          key: cifar-linprobe-data-{{ .Branch }}
          paths:
            - "/home/circleci/project/data"
      - run:
          name: Run CIFAR linear probe
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            python eval/cifar_lin_probe/run_cifar_lin_probe.py \
              data_root=$PWD/data/
  eaif_mujoco:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - initialize
      - restore_cache:
          key: deps9-mujoco200
      - run:
          name: Download and install Mujoco binaries
          command: |
            if [ ! -d "/home/circleci/.mujoco/" ]
            then
                echo "Mujoco does not exist, downloading..."

                mkdir -p /home/circleci/.mujoco/
                cd /home/circleci/.mujoco/

                echo "Getting Mujoco key..."
                curl https://www.roboti.us/file/mjkey.txt > mjkey.txt

                echo "Getting Mujoco 200 binaries..."
                curl https://www.roboti.us/download/mujoco200_linux.zip > mujoco200_linux.zip
                unzip mujoco200_linux.zip
                mv ./mujoco200_linux ./mujoco200
                rm mujoco200_linux.zip
            fi
      - save_cache:
          key: deps9-mujoco200
          paths:
            - "/home/circleci/.mujoco/"
      - run:
          name: Install eaif-models
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            pip install -e ./eaif-models
      - run:
          name: Install Mujoco dependencies
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif

            pip install -e ./third_party/mujoco-py
            pip install -e ./third_party/mj_envs
            pip install -e ./third_party/mjrl
            pip install -e ./third_party/dmc2gym
      - run:
          name: Install Mujoco visual IL library
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif

            pip install -e ./eval/eaif_mujoco
      - run:
          name: Install required apt packages
          command: |
            sudo apt update
            sudo apt install -y xvfb libglew-dev
      - run:
          name: Run pytest
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif

            Xvfb :100 -screen 0 1024x768x24 &
            export DISPLAY=:100
            export LD_LIBRARY_PATH=/home/circleci/.mujoco/mujoco200/bin:$LD_LIBRARY_PATH

            DISPLAY=:100 pytest eval/eaif_mujoco/tests --nocluster

            sudo pkill Xvfb

workflows:
  build:
    jobs:
      - load-models
      - cifar-linprobe
      - eaif_mujoco
