version: 2.1

commands:
  initialize:
    steps:
      - run:
          name: Initialize Git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Delete extraneous circleci stuff
          # This is extremely important for some esoteric $PATH issues involving mrp, Python subprocess, and /bin/bash
          command: rm -rf ~/.circlerc
      - run:
          name: Install Miniconda3
          command: |
            if [ ! -d ~/miniconda3 ]; then
              wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
              /bin/bash ~/miniconda.sh -b -p ~/miniconda3
              rm ~/miniconda.sh
            fi
            sudo ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
            echo ". ~/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc
            echo "conda activate base" >> ~/.bashrc
      - run:
          name: Install mamba
          command: |
            . ~/miniconda3/bin/activate
            conda install -y -c conda-forge mamba -n base

jobs:
  build:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.small
    steps:
      - checkout
      - initialize
      - restore_cache:
          key: deps9-{{ arch }}-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          name: Create conda environment
          command: |
            . ~/miniconda3/bin/activate
            [ -d ~/miniconda3/envs/eaif ] || mamba env create -f environment.yml
      - save_cache:
          key: deps9-{{ arch }}-{{ .Branch }}-{{ checksum "environment.yml" }}
          paths:
            - "/home/circleci/miniconda3/"
  cifar-linprobe:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - initialize
      - restore_cache:
          key: deps9-{{ arch }}-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          name: Install eaif-models
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            pip install -e ./eaif-models
      - restore_cache:
          key: cifar-linprobe-data-{{ .Branch }}
      - run:
          name: Download CIFAR dataset
          command: |
            if [ ! -f ./data/cifar-10-python.tar.gz ]
            then
              . ~/miniconda3/bin/activate
              conda activate eaif
              python -c "import torchvision; torchvision.datasets.CIFAR10(root='./data', download=True)"
            fi
      - run:
          name: Download pretrained checkpoint
          command: |
            export FNAME="mae_pretrain_vit_large.pth"
            if [ ! -f ./data/$FNAME ]
            then
              curl https://dl.fbaipublicfiles.com/mae/pretrain/$FNAME > ./data/$FNAME
            fi
      - save_cache:
          key: cifar-linprobe-data-{{ .Branch }}
          paths:
            - "/home/circleci/project/data"
      - run:
          name: Run CIFAR linear probe
          command: |
            . ~/miniconda3/bin/activate
            conda activate eaif
            python eval/cifar_lin_probe/run_cifar_lin_probe.py \
              data_root=$PWD/data/ \
              model.checkpoint_path=$PWD/data/mae_pretrain_vit_large.pth

workflows:
  build:
    jobs:
      - build
      - cifar-linprobe:
          requires:
            - build
