version: 2.1
jobs:
  cifar-linprobe:
    machine:
      image: ubuntu-2004-cuda-11.4:202110-01
    resource_class: gpu.nvidia.medium
    steps:
      - checkout
      - run:
          name: Initialize Git submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Delete extraneous circleci stuff
          # This is extremely important for some esoteric $PATH issues involving mrp, Python subprocess, and /bin/bash
          command: rm -rf ~/.circlerc
      - run:
          name: Install Miniconda3
          command: |
            if [ ! -d ~/miniconda3 ]; then
              wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
              /bin/bash ~/miniconda.sh -b -p ~/miniconda3
              rm ~/miniconda.sh
            fi
            sudo ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
            echo ". ~/miniconda3/etc/profile.d/conda.sh" >> ~/.bashrc
            echo "conda activate base" >> ~/.bashrc
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "eval/cifar_linprobe/environment.yml" }}
      - run:
          name: Install mamba
          command: |
            . ~/miniconda3/bin/activate
            conda install -y -c conda-forge mamba -n base
      - run:
          name: Create conda environment
          command: |
            . ~/miniconda3/bin/activate
            [ -d /opt/conda/envs/cifar_linprobe ] || mamba env create -f eval/cifar_linprobe/environment.yml
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "eval/cifar_linprobe/environment.yml" }}
          paths:
            - "/home/circleci/miniconda3/envs"
      - run:
          name: Install eaif-models
          command: |
            . ~/miniconda3/bin/activate
            conda activate cifar_linprobe
            pip install -e ./eaif-models

workflows:
  build:
    jobs:
      - cifar-linprobe
