name: "bc_finetune"
lr: 1e-4
visual_lr: 1e-4
batch_size: 16
state_type: "obj"
pretrained_rep: "mae_vit_base_patch16_ego4d_210_epochs"
goal_type: "goal_cond"
n_outer_iter: 500
n_epoch_every_log: 100
latent_dim: none
freeze_pretrained_rep: true
run_sim: true
max_demo_per_diff: 10

image_aug_dict: {
  augment_prob: 0.0, 
  times_to_use_demo: 1, 
  jitter_brightness: 0.3,
  jitter_contrast: 0.3,
  jitter_saturation: 0.3, 
  jitter_hue: 0.03,
  shift_pad: 10,
}
