name: policy_opt
action_lr: 1e-3
n_inner_iter: 100
n_outer_iter: 1
n_epoch_every_log: 10
mpc_type: learned
mpc_forward_model_ckpt: /private/home/clairelchen/projects/logs/multirun/2022-08-22/exp_forward_model_exp_4-2022-08-22-11-55-15/8/ckpts/epoch_400_ckpt.pth
cost_state: obj
cost_type: Weighted
train_forward_model: False
forward_model_n_epochs: 250
policy_type: nn
optimizer: sgd
