env_name: "PointMass-v0"
env_settings:
  params:
    _target_: imitation_learning.utils.envs.pointmass.PointMassParams
    start_state_noise: 0.0
    dt: 0.25
    ep_horizon: 5
    random_start_region_sample: False
  set_eval: False


