_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_contrastive_vit
  checkpoint_path: /checkpoint/yixinlin/eaif/models/adaptation/moco_modified/mae_vitb_scaling1_mobilepick_v1.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  pretrain_algo: "mae"
  adapt_algo: "moco++"
  starting_pt: "/checkpoint/yixinlin/eaif/models/scaling_hypothesis_mae/mae_vit_base_ego_inav_233_epochs.pth"
  pretrain_data:
    - ego
    - inav
  adapt_data: "MobilePick data (50K frames)"
  model: vit_base_patch16
  comment: MobilePick representation finetuned from MAE model trained on scaling datasets
