default:
    - override hydra/launcher: local
    - override hydra/output: local

# general inputs
env               :   None
algorithm         :   BC
pixel_based       :   True                    # pixel based (True) or state based (False) experiment
embedding         :   None                    # choice of embedding network
camera            :   vil_camera              # choice of camera to use for image generation
device            :   cuda
data_dir          :   /home/aryanjain/data/
data_parallel     :   True

# experiment and evaluation
seed              :   12345                   # used as base_seed for rolling out policy for eval in sample_paths
epochs            :   100                     # number of outer epochs
eval_frequency    :   10                      # frequency of epochs for evaluation and logging
save_frequency    :   10                      # frequency of epochs for saving policies
eval_num_traj     :   25                      # number of rollouts to eval
video_num_traj    :   5                       # number of evaluation rollouts to save as video
num_cpu           :   1                       # for rolling out paths when evaluating                 
num_demos         :   100                     # path to demo file auto-inferred from other inputs
exp_notes         :   Adroit run with context_length=3 and delta features from Flare. Running for more epochs.

# environment related kwargs
env_kwargs:
    env_name      :   ${env}                
    device        :   ${device}               # device to use for representation network (policy clamped to CPU for now)
    image_width   :   256
    image_height  :   256
    camera_name   :   ${camera}
    embedding_name :  ${embedding}                
    pixel_based   :   ${pixel_based}
    render_gpu_id :   0
    seed          :   ${seed}
    history_window :  3   

# demo reparsing arguments (states -> image embeddings)
reparse_kwargs:
    visualize     :   False                   # store videos (.mp4) of the trajectory while reparsing
    save_frames   :   False                   # save the generated images in the trajectory (can increase storage space dramatically)

# BC agent setup
bc_kwargs:
    hidden_sizes  :   (256, 256, 256)
    nonlinearity  :   relu
    loss_type     :   'MSE'
    batch_size    :   256
    lr            :   1e-3
    dropout       :   0

# logging
wandb_project     :   rep_eval_visual_il

# general outputs
job_name          :   'job'

hydra:
    job:
        name  : VIL_conv_comp_runs
        chdir : True
