ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v2
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR', 'DEMONSTRATION_SENSOR', 'INFLECTION_WEIGHT_SENSOR']
  GOAL_SENSOR_UUID: objectgoal
  DEMONSTRATION_SENSOR:
    TYPE: DemonstrationSensor
  DEMONSTRATION_SENSOR_UUID: "demonstration"
  INFLECTION_WEIGHT_SENSOR:
    TYPE: InflectionWeightSensor
    INFLECTION_COEF: 3.477512060914205
  INFLECTION_WEIGHT_SENSOR_UUID: "inflection_weight"

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

  SUCCESS:
    SUCCESS_DISTANCE: 0.1

SEED: 103
DATASET:
  TYPE: ObjectNav-v2
  SPLIT: train
  DATA_PATH: "data/datasets/objectnav/objectnav_hm3d/objectnav_hm3d_10k/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
  MAX_EPISODE_STEPS: 500

