defaults:
  - _self_
  - tasks@: objectnav_hm3d_il
  - experiments@: objectnav_il
  - model: dino_resnet50_omnidata
  - model/transform: jitter_and_shift_objectnav
  - wandb_habitat@: habitat_objectnav_eaif
  - override hydra/output: path
  - override hydra/launcher: slurm_train

RUN_TYPE: train
NUM_ENVIRONMENTS: 16
hydra:
  launcher:
    nodes: 4

