defaults:
  - _self_
  - tasks@: objectnav_hm3d_rl
  - experiments@: objectnav_rl
  - model: dino_resnet50_omnidata
  - model/transform: jitter_and_shift_objectnav
  - wandb_habitat@: habitat_eaif
  - override hydra/output: path
  - override hydra/launcher: slurm_train

RUN_TYPE: train
NUM_ENVIRONMENTS: 12
hydra.launcher.nodes: 5
