defaults:
    - _self_
    - algo: bc_finetune

demo_path: demos/preloaded_demos/demos_d-1_train-1_test-1_scale-100.pth
no_wandb: True
run_id: ${hydra:job.num}
seed: 10

hydra:
    sweep:
        dir: multirun/${now:%Y-%m-%d}/exp_${hydra.runtime.choices.experiment}-${now:%Y-%m-%d}-${now:%H-%M-%S}
        subdir: ${hydra.job.num}

