setting: multitask
algorithm: mtdmpc
encoder: default+
enc_dim: 512
mlp_dim: 1024
latent_dim: 50
fraction: 1.0
train_iter: 200000
lr: 1e-3
batch_size: 64
lazy_load: true
cache_size: 2000000
num_workers: 8
prefetch_factor: 4
fetch_every: 12
