# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
cpus_per_task: 10
gpus_per_node: 1
tasks_per_node: 1
timeout_min: 600
mem_gb: 64
nodes: 1
name: ${hydra.job.name}
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
