CUDA_VISIBLE_DEVICES=1 python train_offline.py \
    task=mw-mt10 \
    suite=mw \
    setting=multitask \
    algorithm=mtdmpc \
    modality=features \
    features=mocoego \
    exp_name=test \
    seed=1
