_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_encoder
  model:
    _target_: eaif_models.models.vit.omnimae_vit.vit_large_mae
    img_size: 224
    patch_size: 16
    global_pool: False
    use_cls: False
    train_cls: True
    patch_embed_type: linear
  train_time_dim: 1
  checkpoint_path: /checkpoint/yixinlin/eaif/results/omnivision/2023-01-12-19-17-04/config/experiments/arjunmajumdar/adaptation/005_mae_adapt_v1.yaml/0/checkpoints/checkpoint_1600.pt
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_large_patch16
  data:
    - ego
    - imagenet
    - inav
    - gibson
  starting_point: /checkpoint/yixinlin/eaif/models/scaling_hypothesis_mae/mae_vit_large_ego_imagenet_inav_182_epochs.pth
  comment: adaptation_experiment_v1
