_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_encoder
  model:
    _target_: eaif_models.models.vit.omnimae_vit.vit_large_mae
    img_size: 224
    patch_size: 16
    global_pool: False
    use_cls: True
    train_cls: True
    patch_embed_type: linear
  train_time_dim: 1
  checkpoint_path: /checkpoint/maksymets/eaif/results/omnivision/2023-01-20-15-24-19/config/experiments/arjunmajumdar/adaptation/006_mae_scratch_v1.yaml/0/checkpoints/checkpoint_1600.pt
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_large_patch16
  data:
    - mujoco_expert_v0_1
  comment: in_domain_ssl_v1
