
model:
  _target_: eaif_models.utils.load_model.MAE_embedding_model
  checkpoint_path: /checkpoint/yixinlin/experiments/61004636/checkpoint-74.pth

embedding_dim: 1024
transform: mae_transforms

device: cuda
batch_size: 32
num_epochs: 25
lr: 1e-3

data_root: "./data"