name: forward_model
lr: 1e-3
n_epochs: 5000
obj_state_type: img_r3m
use_ftpos: True
n_epoch_every_save: 100
hidden_dims: 100
path_to_decoder_ckpt: /private/home/clairelchen/projects/trifinger_claire/multirun/2022-08-15/exp_decoder_exp_1-2022-08-15-18-17-52/2/ckpts/epoch_2000_ckpt.pth
