name: mbirl
cost_type: Traj
cost_lr: 1e-2
action_lr: 1e-2
n_inner_iter: 1
cost_state: ftpos
irl_loss_state: ftpos
rbf_kernels: 5
rbf_width: 2
n_outer_iter: 500
n_epoch_every_log: 50
mpc_type: ftpos
mpc_forward_model_ckpt: null
path_to_decoder_ckpt: null
