name: policy_opt
action_lr: 1e-3
n_inner_iter: 10000
n_epoch_every_log: 100
mpc_type: learned
mpc_forward_model_ckpt: null
path_to_decoder_ckpt: null
cost_state: obj
train_forward_model: True
forward_model_n_epochs: 250
