ENVIRONMENT:
  MAX_EPISODE_STEPS: 1000

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  AGENT_0:
    SENSORS: ["RGB_SENSOR"]
  RGB_SENSOR:
    WIDTH: 128
    HEIGHT: 128

TASK:
  TYPE: Nav-v0
  SUCCESS:
    SUCCESS_DISTANCE: 1.0
  TRAIN_SUCCESS:
    SUCCESS_DISTANCE: 0.8
  SUCCESS_DISTANCE: 1.0
  SIMPLE_REWARD:
    SUCCESS_REWARD: 5.0
    ANGLE_SUCCESS_REWARD: 5.0
    USE_DTG_REWARD: True
    USE_ATG_REWARD: True
    ATG_REWARD_DISTANCE: 1.0
    SLACK_PENALTY: -0.01
  SENSORS: ["IMAGEGOAL_ROTATION_SENSOR"]
  MEASUREMENTS: [
    "DISTANCE_TO_GOAL",
    "SUCCESS",
    "TRAIN_SUCCESS",
    "ANGLE_TO_GOAL",
    "ANGLE_SUCCESS",
    "SPL",
    "SOFT_SPL",
    "SIMPLE_REWARD",
  ]

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: data/datasets/imagenav/gibson/v1/{split}/{split}.json.gz
