defaults:
  - _self_
  - pretrain@: config 

ngpus: 8
nodes: 2
timeout: 4320
mem_gb: 512
partition: learnlab
use_volta32: True
comment: ""

# params filled by submitit
gpu: 0
rank: 0
dist_backend: nccl