_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.clip.load_clip_vit_checkpoint
  checkpoint_path: /checkpoint/yixinlin/eaif/models/clip/ViT-B-16.pt
  model:
    _target_: eaif_models.models.vit.vit.clip_vit_base_patch16
    use_cls: true
    del_head: false
transform:
  _target_: eaif_models.transforms.clip_transforms
  resize_size: 224
  output_size: 224
metadata:
  algo: clip
  model: vit_base_patch16
  data: wit
