_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/models/mae_ego4d/mae_pretrain_vit_small_ego4d.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_small_patch16
    img_size: 224
    global_pool: True
    drop_path_rate: 0.0
transform:
  _target_: hydra.utils._locate
  path: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_small_patch16
  data: ego4d
