_target_: eaif_models.models.vit.vit_mae.load_model
checkpoint_path: /checkpoint/yixinlin/eaif/models/mae_habitat/mae_vit_small_decoder_large_HGSP_RE10K_100.pth
model_name: mae_vit_small_patch16_large_decoder
metadata:
  algo: mae
  model: vits
  data: HGSP
