_target_: eaif_models.models.vit.vit.load_model
checkpoint_path: /checkpoint/yixinlin/eaif/models/mae_habitat/mae_vit_small_decoder_large_HGSP_RE10K_100.pth
model_name: vit_small_patch16
model_config:
  img_size: 224
  global_pool: False
  use_cls: True
  mask_ratio: 0.0
  drop_path_rate: 0.0
metadata:
  algo: mae
  model: mae_vit_small_patch16_large_decoder
  data: HGSP+RE10K
