_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_encoder
  model:
    _target_: eaif_models.models.vit.vit.vit_large_patch16
    global_pool: true
  checkpoint_path: /checkpoint/yixinlin/eaif/models/mae/mae_pretrain_vit_large.pth
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_large_patch16
  data: imagenet
