_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_encoder
  model:
    _target_: eaif_models.models.vit.omnimae_vit.vit_base_mae
    img_size: 224
    patch_size: 16
    global_pool: False
    use_cls: False
    train_cls: True
    patch_embed_type: linear
  train_time_dim: 1
  checkpoint_path: /checkpoint/yixinlin/eaif/models/omnimae/001_mae_image_hgsp_vitb_799_epochs.pt
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mae
  model: vit_base_patch16
  data: HGSP
  comment: 800_epochs_omnimae
