_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_mae_encoder
  model:
    _target_: eaif_models.models.vit.vit.vit_large_patch16
    use_cls: True
  checkpoint_path: /checkpoint/yixinlin/eaif/models/mvp/vit_l.pth
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: mvp
  model: vit_large_patch16
  data:
    - ego4d
    - hoi
    - imagenet
