_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.vit_base_mae_finetune_in1k
checkpoint_dict:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_checkpoint
  checkpoint_path: /checkpoint/yixinlin/eaif/models/omnimae/vitb_in1k_ft.torch
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: omnimae
  model: vit_base_patch16
  data:
    - imagenet
    - ssv2
  comment: finetune_imagenet