_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_contrastive_vit
  checkpoint_path: /checkpoint/yixinlin/eaif/models/r3m/v110/r3m_vit_base_patch16_ego4d.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  tag: r3m-v110_vitb_ego4d
  algo: r3m
  model: vit_base_patch16
  data: ego4d
