_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_encoder
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    global_pool: true
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: rand
  model: vit_base
  data: none
