_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.resnet.resnet.resnet50
  weights: # None, as this is randomly initialized
transform:
  _target_: eaif_models.transforms.resnet_transforms
metadata:
  algo: rand
  model: resnet50
  data: none
