_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.resnet.resnet.resnet50
  weights: IMAGENET1K_V2
transform:
  _target_: hydra.utils._locate
  path: eaif_models.transforms.resnet_transforms
metadata:
  algo: sup
  model: resnet50
  data: imagenet
