_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_encoder
  model:
    _target_: eaif_models.models.vit.omnimae_vit.vit_base_mae
    patch_embed_type: tmae
  checkpoint_path: /checkpoint/yixinlin/eaif/models/tmae/tmae_video_ego4d_hgsp_vitb_165.pt
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: tmae
  model: vit_base_patch16
  data:
    - ego4d
    - hgsp
