_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.omnimae_vit.load_omnimae_encoder
  model:
    _target_: eaif_models.models.vit.omnimae_vit.vit_base_mae
    img_size: [3, 4, 224, 224]
    patch_size: [1, 16, 16]
    global_pool: False
    use_cls: False
    train_cls: False
    patch_embed_type: tmae
  train_time_dim: 4
  checkpoint_path: /checkpoint/yixinlin/eaif/models/omnimae/007_tmae_video_hgsp_vitb_large_decoder_new_masking_v2.pt
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: tmae
  model: vit_base_patch16
  data: hgsp
  comment: large_decoder_new_masking_v2
