_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/results/vip_training/vip_vit_small_Ego4D/2022-10-14_21-32-44/checkpoint.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_small_patch16
    img_size: 224
    # global_pool: True
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: vip
  model: vit_small_patch16
  data: ego4d
