_target_: eaif_models.models.load_model
model:
  _target_: eaif_models.models.vit.vit.load_encoder
  checkpoint_path: /checkpoint/yixinlin/eaif/models/vip/vit/vip_vit_base_patch16_ego4d_130_epochs.pth
  model:
    _target_: eaif_models.models.vit.vit.vit_base_patch16
    img_size: 224
    use_cls: True
    drop_path_rate: 0.0
transform:
  _target_: eaif_models.transforms.vit_transforms
metadata:
  algo: vip
  model: vit_base_patch16
  data: ego4d
  comment: 130_epochs
